export enum EntityType {
  PROJECT = 'PROJECT',
  FOLDER = 'FOLDER',
  ALL = 'ALL',
  TODAY = 'TODAY',
  TOMORROW = 'TOMORROW',
  NEXT_SEVEN_DAYS = 'NEXT_SEVEN_DAYS',
  ASSIGNED_TO_ME = 'ASSIGNED_TO_ME',
  INBOX = 'INBOX',
  SUMMARY = 'SUMMARY',
  TAG = 'TAG',
  CHILD_TAG = 'CHILD_TAG'
}
